src/actions/petitionActions.js, src/components/petition.js, src/components/signature-add-form.js, src/main.js, src/pages/sign-petition.js
I think this is functionally the same, with less code, but maybe I'm missing something?
=> remove mapDispatchToProps, and instead import  actions directly

README.md
=> add travis status badge to README

docs/REFERENCE--environment_variables.md
=> add documentation of environment variables

.travis.yml, package.json, src/components/petition.js, src/components/signature-add-form.js, src/lib.js, src/loaders/petition.js
Fixing last lint errors, for #15.
=> Remove unused placeholder code and add text2paraJsx lib function

.travis.yml, package.json, src/components/petition.js, src/components/signature-add-form.js, src/lib.js, src/loaders/petition.js
For #20.
Note: this assumes #19, so that should be reviewed and merged before this is reviewed.
=> lint and test

.travis.yml, src/actions/petitionActions.js, src/components/petition.js, src/components/signature-list-item.js, src/components/signature-list-page.js, src/components/signature-list.js, src/lib.js, src/loaders/petition.js, src/reducers/index.js
For #18, this adds signature list display to petition pages.
=> Signature display

src/pages/search.js, src/routes.js
Hey @sreynen - you created several issues like this. Were you thinking something like this for the route creation issues?
=> Adds search page route and search component

src/pages/home.js, src/routes.js
=> Adds route for home page and simple component

src/pages/petition-creator-dashboard.js, src/routes.js
=> Adds route for petition creator dashboard and simple component

src/pages/create-petition-page.js, src/routes.js
fixes https://github.com/MoveOnOrg/mop-frontend/issues/26
=> Adds create petition route and simple component

src/components/recentvictory.js, src/pages/home.js
=> 53 recent victories component

docs/REFERENCE--environment_variables.md, local/api/v1/petitions/outkast.json, src/actions/petitionActions.js, src/components/petition.js, src/components/signature-add-form.js, src/components/thanks.js, src/config.js, src/pages/sign-petition.js, src/reducers/index.js, webpack.config.js
Figured I should do a push and a code-review before continuing. This implements:
* shareclick tracking, 
* sharebandit support, 
* fixes sign-page html a bit (class => className, etc)
* thanks redirect in actions instead of page, to fix back button
Still todo (for future PRs):
* google analytics 'conversion' tracking
* short code/urls (for the anonymous signature use-case)
* next petition
=> thanks page (more work)

package.json
=> fix path glob for eslint, so it checks subdirectories

src/components/nav-link.js, src/components/nav.js, src/components/petition-preview.js, src/lib.js
For #95, but also found in the process some of the links didn't match the live site, and since all the links have the same markup, moved that to a separate component to ease future restyling.
=> update session checks for nav, add reusable navlink component, and update links

src/components/wrapper.js
=> Adds hr element for redline

src/actions/sessionActions.js
Fixes #123 per https://www.npmjs.com/package/whatwg-fetch#sending-cookies
=> add credentials flag to session request, to send cookies

src/components/signature-add-form.js
* show_optin in osdi so we know whether they opted OUT
=> more stuff for frontend to send signatures

docs/HOWTO--deploy-to-s3.md, docs/REFERENCE--environment_variables.md, src/actions/petitionActions.js, src/components/signature-add-form.js, src/config.js, test/components/signature-add-form.js, test/store/petition-load.js, webpack.config.js
and also add a API_SIGN_PETITION override that can go anywhere
=> make our API_URI do what our docs say, 

README.md, package.json
I'll update the deploy docs, but this makes main.js 1.1M => main.js 169K
=> remove debug choice as build default

src/components/nav.js
=> fix apostrophe in dashboard link

src/actions/petitionActions.js, src/pages/thanks.js
We need to send the right Content-Type with the osdi petition signature.
=> send proper content-type for signPetition

src/components/search-results.js, test/components/search-results.js
lint was right and i was wrong
=> fix legit bug caught by lint. thanks lint

local/api/v1/signatures.json, src/actions/petitionActions.js, src/pages/thanks.js
This fixes, and also makes it possible to test locally with API_WRITABLE=fake
=> md5Message was not propagating to thanks page. 

src/actions/sessionActions.js
=> remove redundant /api/v1 from path

local/index.html, local/sign/economic-disparity-campaign, local/thanks.html
Fixes #174. (Separate fix for backend.)
=> add font CSS to local for testing

src/components/signature-list-item.js
#186 
I did what the live site does and used the browser confirm() method.  Would it be better to create a modal component and do something like https://getbootstrap.com/docs/3.3/javascript/#modals?
=> Add Confirmation Dialog to Flag Signature Comment

src/actions/accountActions.js, src/components/register-form.js, src/pages/register.js, src/reducers/index.js, src/routes.js
#150
Not really sure about the server api so I just loosely filled in the actions and reducers.  Would it be better to incorporate the register reducer with the session reducer?
=> Add Register Page and Component WIP

src/components/form/state-select.js, src/components/searchbar.js, src/pages/home.js
=> Fixes spacing and inline styling for search bar component on homepage

src/components/search-results.js
=> Adds ... after blurb

src/components/create-petition-form.js
=> Removes more_option selector that hides div

src/components/create-petition-form.js, src/components/form/instructions/about.js, src/components/form/instructions/statement.js, src/components/form/instructions/target-custom.js, src/components/form/instructions/target-national.js, src/components/form/instructions/target-state.js, src/components/form/instructions/title.js, src/components/form/target-select/custom.js, src/components/form/target-select/national.js, src/components/form/target-select/state.js
Fixes #204. Moves all the conditional markup to separate components, for better readability and easier  updates.
=> move conditional sections of form to separate components

src/components/footer.js
=> Fixes footer to match logged out state in prod

src/components/billboard.js
=> Removes inline styling and switches to Link component

package.json, src/components/login-form.js, src/components/register-form.js, src/lib.js, src/pages/login.js, src/routes.js, test/components/login-form.js, test/pages/login.js
closes #147 
Next step would be #148, to make login work.
Again, there was a lot in common with https://github.com/MoveOnOrg/mop-frontend/blob/master/src/components/register-form.js
=> Add login page (that doesn't work yet)

src/components/form/target-select/custom.js
=> 234 custom target creation

src/components/search-result-pagination.js
=> 210 search loading

src/components/petition.js
=> Disclaimer text for sign page

src/actions/accountActions.js, src/components/forgot-password-form.js, src/pages/forgot-password.js, src/routes.js, test/pages/forgot-password.js
closes #149
api issue: https://github.com/MoveOnOrg/mop/issues/150
Creates http://localhost:8080/#/login/forgot_password.html
For simplicity I have left out:
- All server errors (email is validated locally though)
- Thank you page doesn't have its own route or component
- Redux is not involved
I took a lot of the validation stuff from user registration. I'm not sure if it's worth extracting? https://github.com/MoveOnOrg/mop-frontend/blob/master/src/components/register-form.js
Open to changing anything!
=> Forgot password page

src/components/legacy/hot-petitions.js, src/components/legacy/petition-preview.js, src/containers/top-petitions.js
Fixes some of #243 
Creates a stateless component `HotPetitions` that is included in the container `TopPetitions`
=> Top petitions refactor

src/actions/navActions.js, src/components/legacy/organization-header.js, src/containers/home.js
Part of #243? Wasn't in the list, but was easy to do.
=> 243 organization header refactor

src/store/configureStore.js
Allows you to see the redux actions when you have the chrome/firefox extension:
https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd
More info: http://extension.remotedev.io
=> Add redux devtools support

.travis.yml
=> Enable only prod routes on travis dev build (broom)

.travis.yml
This is in preparation of switching the default branch to main.
=> switch travis deploy to main branch

src/reducers/index.js, test/reducers/petition.js
Repeat of https://github.com/MoveOnOrg/mop-frontend/pull/299 against new default branch
=> Petition reducer tests

package.json, src/components/theme-giraffe/wrapper.js, src/components/theme-legacy/wrapper.js, src/containers/create-petition.js, src/containers/forgot-password.js, src/containers/login.js, src/containers/register.js, src/containers/search.js, src/containers/sign-petition.js, src/containers/static.js, src/containers/thanks.js
fixes #315 
See https://github.com/gaearon/react-document-title for an explanation of the component I use. I think it's a pretty small dependency, and it fits pretty well with our container elements that aren't deeply nested.
The legacy system doesn't actually have that many titles, so I based most of these on the header of the page.
=> Update document title as route changes

local/api/v1/petitions/list96069/signatures.json, src/actions/petitionActions.js, src/components/theme-giraffe/petition.js, src/components/theme-legacy/petition.js, src/containers/signature-list.js
fixes #331
My guess is that this is not the most elegant code for react/es6 style.  I'd love feedback on how this would be better written in a regular style.
=> get signatures by list id rather than slug

src/components/theme-giraffe/petition.js, src/components/theme-giraffe/signature-add-form.js, src/containers/sign-petition.js, src/containers/signature-add-form.js, src/giraffe-ui/modal.js, src/giraffe-ui/petition/input-block.js
Same as #322 , which was merged into the wrong branch
=> Add giraffe mobile signing modal (attempt 2)

src/components/theme-giraffe/petition.js, src/components/theme-legacy/petition-message.js, src/components/theme-legacy/petition.js, src/giraffe-ui/petition/index.js, src/giraffe-ui/petition/message.js, test/components/giraffe-petition.js
=> Don't display unverified message when petition is status is 'Bad'

webpack.config.js
forces chunks to be loaded anew through prod caching
=> change chunk file query for each new build

src/reducers/index.js
Found by our  nice devtool merged in #312
=> Fix a reducer state mutation

src/routes.js
=> add two new static pages

.babelrc, package.json, src/apps/main.js, src/apps/nav-only-routes.js, src/apps/nav-only.js, src/apps/polyfills.js
Fixes #358
I tested that signing a petition works on ie 11 (at least on dev) except for #366
=> Add Object.assign and Promise polyfills for ie 11

src/components/theme-legacy/recentvictory.js
Fixes #366 
Maybe this should be moved to moui.css though?
=> Fix article image size in ie 11

package.json, src/components/theme-legacy/wrapper.js, src/containers/thanks-next-petition.js
Use [react-portal](https://github.com/tajo/react-portal) to render ThanksNextPetition in a div included in the Wrapper
Fixes #360
=> Make thanks.html redirect message appear at top of screen

src/actions/petitionActions.js, src/containers/thanks.js, src/lib/index.js
=>  Track list_id and r_hash on share

.travis.yml
=> send record_share_click on stage

src/actions/petitionActions.js, src/lib/index.js
=> Stringify params for form-urlencoded

local/index.html, src/components/theme-giraffe/signature-add-form.js, src/components/theme-legacy/signature-add-form.js, src/containers/signature-add-form.js, src/giraffe-ui/petition/input-block.js, webpack.config.js
- Don't include moui in giraffe in dev
- Correct design for checkboxes in giraffe sign form
- Make validation text red
- Giraffe styles don't need value from state anymore
- Use helper methods for setting thirdparty_optin in state
=> Fixes for the giraffe sign form

src/containers/hoc-share-message.js
=> up statement max to 600 in email shares

src/containers/signature-add-form.js, test/components/signature-add-form.js
=> Fix logic to hide sign form address when user is signing petition

src/components/theme-legacy/petition-message.js
Use portal to make petition messages appear at the top of the screen (like the thanks message)
=> Use portal for petition message

src/components/theme-giraffe/billboard.js, src/components/theme-giraffe/blurb.js, src/components/theme-giraffe/home.js, src/components/theme-giraffe/hot-petitions.js, src/components/theme-giraffe/long-search-bar.js, src/components/theme-giraffe/signature-add-form.js, src/components/theme-giraffe/victories.js, src/containers/blurb.js, src/containers/home.js, src/containers/searchbar.js, src/containers/top-petitions.js, src/containers/victories.js, src/giraffe-ui/blurb.js, src/giraffe-ui/button.js, src/giraffe-ui/petition/state-select.js, test/components/searchbar.js, test/pages/home.js
fixes #372
Let me know if you have any feedback.
=> Add giraffe home components

src/components/theme-giraffe/nav.js
=> Final nav links

src/components/theme-giraffe/petition.js, test/components/giraffe-petition.js
=> Don't truncate giraffe petition summary

src/components/theme-giraffe/petition.js
=> Text change

src/components/theme-giraffe/signature-add-form.js, src/giraffe-ui/button.js
This will need a corresponding change in giraffe CSS.
=> change text and class on submit button

src/components/theme-giraffe/petition.js, src/components/theme-giraffe/signature-add-form.js, src/containers/sign-petition.js, src/containers/signature-add-form.js, src/giraffe-ui/petition/floating-sign-button.js
It has a fixed offset that we can specify, so hopefully it doesn't end up behind the nav.
I haven't tested this much yet.
=> Use scrollchor to scroll from the sign now button

src/components/theme-giraffe/long-search-bar.js
=> Change state selector text on giraffe homepage

package.json, src/containers/signature-add-form.js, src/lib/index.js
We can't uglify this module because it's not transpiled
So I got the regex directly from https://github.com/sindresorhus/email-regex/blob/master/index.js
Fixes #456
=> Use different email regex from email-regex

src/routes.js
=> mark /sign/ and /pac/ routes prodReady

src/components/theme-giraffe/petition.js, src/components/theme-giraffe/signature-add-form.js, src/giraffe-ui/petition/card.js, src/giraffe-ui/petition/containers.js
Part of https://github.com/MoveOnOrg/mop-frontend/issues/459
=> Redesign sign page

src/components/theme-giraffe/signature-add-form.js, src/containers/signature-add-form.js, test/components/signature-add-form.js
=> Hide address fields until interaction with form on giraffe

src/giraffe-ui/petition/card.js
=> Add signature count copy

src/components/theme-giraffe/nav.js
=> Add minimal nav theme for giraffe that hides links

src/components/theme-giraffe/signature-add-form.js
=> Add back blue sign form background

src/containers/cobrand-logo.js, src/containers/sign-petition.js, src/containers/wrapper.js
corresponding backend issue:
https://github.com/MoveOnOrg/mop/pull/360
e.g. https://petitions.moveon.org/sign/cursive-writing-is-a.fb50?source=c.fb
=> support petition-slug suffixes like .fb123 or .html

webpack.config.js
I didn't know a better way of doing this besides the refactor
=> Use env var for bundle analyzer webpack plugin

src/actions/sessionActions.js
=> Try identifying for segment on page load

src/components/theme-giraffe/footer.js, src/components/theme-giraffe/nav.js
fixes #479
Note: This is not created against the main branch. So merge this first, then #480, or change the base branch to main.
=> Update nav and footer

src/components/theme-giraffe/home.js
fixes #487 
Make it the same as https://github.com/MoveOnOrg/mop-frontend/blob/main/src/components/theme-legacy/home.js#L9
Also I tested locally
=> Fix pac home

src/giraffe-ui/logo.js
=> Change logo to link to front.moveon.org

src/giraffe-ui/logo.js
With giraffe and mop PRs:
https://github.com/MoveOnOrg/giraffe/pull/233
https://github.com/MoveOnOrg/mop/pull/380
this will allow loading the svg inline, if available.
=> allow inline logo if available

src/components/theme-giraffe/nav.js
=> Add manage petitions link

src/containers/sign-petition.js
Reverts MoveOnOrg/mop-frontend#441
https://github.com/MoveOnOrg/mop/pull/348 solves this for realz
=> Revert "Temp fix firefox redirect"

src/components/theme-giraffe/petition-message.js, src/components/theme-giraffe/petition.js, src/components/theme-legacy/petition-message.js, src/components/theme-legacy/petition.js, src/containers/sign-petition.js
=> Move petition outOfDate into petitionMessage and make sure its a bool

.travis.yml
To make it easier to test work in progress
=> Remove ONLY_PROD_ROUTES from staging build

src/containers/create-petition-target.js, src/containers/petition-creator-dashboard.js
Mostly https://github.com/yannickcr/eslint-plugin-react/pull/1771
=> Fix linting errors

src/reducers/petition-targets.js
=> fixed typo in target selection interface

src/containers/signature-list-item.js, test/components/signature-list-item.js
=> Handle empty location in signature

src/actions/accountActions.js, src/components/theme-legacy/create-preview.js, src/containers/register-form.js, src/lib/index.js
closes #553 
some context in https://github.com/MoveOnOrg/mop/issues/381
=> Display special error if the account exists and creating a petition

src/components/theme-legacy/form/target-select/legislator-autocomplete.js
=> Add loading state to petition target create legislator autocomplete

docs/EXPLANATION--cohort-testing.md, src/components/theme-giraffe/signature-add-form.js, src/containers/sign-petition.js, src/containers/signature-add-form.js, src/giraffe-ui/input-block.js, src/routes.js, test/components/signature-add-form.js
=> 585 perm mobile field

src/lib/index.js
hotmaill.com suggesting gmail.com by stopping after a warning is found
=> fix gmail/hotmail suggestion

src/containers/signature-add-form.js, test/components/signature-add-form.js
=> 587 dynamic sms follow up

src/containers/hoc-copy-link.js, src/containers/thanks.js
=> recordShare for raw links

src/containers/thanks.js, src/lib/cohort-tracker.js, src/lib/index.js
Adds cohort tracker to tell segment when whatsapp button is displayed
=> WIP: Cohort Tracker for Segment for WhatsApp

src/actions/sessionActions.js, src/containers/thanks.js, src/lib/cohort-tracker.js, src/lib/index.js
(cherry picked from commit 717afd0c35a4c38488230a092722883a37936ada)
Originally apart of #601 and #598
=> Change Testing Size Capabilities and Adds Tracking to Segment for WA test

package.json
until this issue is resolved: https://github.com/webpack/webpack/issues/8656
=> pin webpack 

src/containers/thanks.js
Changing the experiment name so we can easily find it in DW.
=> updates experiment name to whatsAppShare2
