MoveOnOrg/mop-frontend

- src/main.js
- src/routes.js
- webpack.config.js
This allows dev loading at e.g. `/#/sign/outkast` instead of `/build/#/sign/outkast`
> Dev base path

- src/actions/petitionActions.js
Preloading didn't seem to be working with just returning the object, and does work with returning the dispatch of the object. Also, preloading signatures wasn't working and maybe isn't worth doing at all, so just removed to potentially add a working version later.
> add dispatch to petition preload and remove signature preload

- .travis.yml
This will auto-deploy changes in master branch to mop-static-stage S3 bucket. This is a step we do for end-to-end testing pretty often, and this would remove that step.
> Travis deploy

- src/components/form/state-or-region-input.js
- src/components/form/state-select.js
- src/components/searchbar.js
for #80 
- note depending on network speed, proper google font may not load which will make the font size/type look slightly different
- most styling comes from static css
- the styling added was to allow us to use state-select logic in different places, but with different styles
- the text refactor was added because petitions.moveon.org state select and sign petition pages on live site have different text in the selector.
> Refactors state select to take text and style

- local/index.html
- package.json
- src/components/petition.js
- src/components/signature-add-form.js
- test/components/signature-add-form.js
- test/lib.js
This also fixes a few bugs that surfaced when setting the tests up:
* putting the mobile-related headers into our index.html
* removing hard-coded content from the add-form (Donald Trump isn't *always* the petition target :-)
* setting up the component for easier testing
> add first two good tests to petition signature-add-form

- docs/HOWTO-write-tests.md
- local/api/v1/organizations/mop.json
- local/api/v1/petitions/outkast-opposite.json
- src/actions/navActions.js
- src/actions/sessionActions.js
- src/components/nav.js
- src/components/wrapper.js
- src/pages/home.js
- src/reducers/index.js
- src/routes.js
- test/pages/home.js
This addresses the last part and completes #69 -- hitting the organization api to get the org data.
There are further tests to add --maybe especially for nav.
There will be more org work esp for supporting orgs within all the other url contexts (sign/thanks/etc)
> load organization data for organization imbued urls

- src/actions/petitionActions.js
- src/components/thanks.js
- src/config.js
- src/lib.js
- src/pages/thanks.js
- src/reducers/index.js
- test/components/thanks.js
- webpack.config.js
This continues work on things that happen when someone signs a petition.
* They get a thank-you email
* on the thanks page, they are offered a short url to share on twitter.  Because in the new system, the react frontend won't have the user_id yet, we need a different kind of short url that we can match up to their signature later, when someone signs from their shared link.  That was architected a while ago with petitions/petition_shortcode.py work, however I didn't finish connecting all the pieces.  Because that short url also needs to exist in the email, this PR also connects more of those pieces.  It also finally decides HOW to construct that token and where to store it -- RateLimit.token and based on the SQS md5 hash of the body (which conveniently will also detect identical content …
> add shorturls for twitter on thanks page and infrastructure for that (/p/ shortcode urls)

- .eslintrc.js
- docs/HOWTO-developer-tips.md
After seeing bad things happen in a PR (commented out code got upper-cased), I would like to remove the auto-capitlize lint.
This also has a stub dev doc, so I can remember how to get react redux store state.
> add a devtips stub and remove capitalized-comments lint

- css/moui.css
- src/components/petition.js
- src/pages/create-petition-page.js
- src/pages/home.js
- src/pages/petition-creator-dashboard.js
- src/pages/search.js
- src/pages/sign-petition.js
- src/pages/thanks.js
This fixes #121, and also similar issues that would eventually come up on other pages. Specifically, it extends the pattern already used on sign pages of making `div.*` versions of all `body.*` classes (except `home` and `donate`, which aren't used on this site), and it adds those classes on every page component.
> Faux-body classes

- src/actions/sessionActions.js
- src/reducers/index.js
After implementing the backend, this resolves some bugs/issues with the original implementation of session api and user state.
* We previously separated cookie loading vs. token loading.  Since a cookie doesn't actually indicate authenticated state, we need to combine them.
* Combining them makes the `TOKEN_SESSION_*` and `USER_SESSION_*` a bit redundant so we collapse them
* signature-add-form assumes if someone is identified then there's a `user.token` but we never implemented that (useful) simplification.  This does that based on parameters from the location and/or the session api data.
> fix user session info

- src/components/footer.js
- src/components/nav.js
- src/components/recentvictory.js
- src/components/signature-add-form.js
- src/components/thanks.js
Change all hard-coded links to https for security and it's 2018.
Most of these are straight changes.  There are two 'special' changes:
1. The press link in our footer now 404s, so I updated it
2. http://moveon.wpengine.netdna-cdn.com/wp-content/uploads/2013/11/NYTimes.jpg and other links from that domain don't support https.  However all the same content is available from the host: `https://front.moveon.org`, e.g. https://front.moveon.org/wp-content/uploads/2013/11/NYTimes.jpg
> convert all http:// => https://

- src/actions/petitionActions.js
- src/components/billboard.js
- src/components/thanks.js
- src/pages/thanks.js
- src/reducers/index.js
This implements two things that were marked TODO:
* passing the  ?from_source= parameter from the sign page to the thanks page and having that change the `pre` variable
* doing some length logic around really long petition statements for the mail message.
This is on top of PR: https://github.com/MoveOnOrg/mop-frontend/pull/165
so we should merge that first, and then I'll rebase this.
> Thanks page finishings

- src/components/signature-add-form.js
- src/components/thanks.js
- test/components/signature-add-form.js
This PR does two things.
1. The first is kinda silly, but instead of showing a 'raw' link to the petition to copy/paste, I create a shortcode link so we can track those -- more appropriate
2. The second was fixing the case of https://petitions.moveon.org/workingfamilies/sign/censure-trump-for-refusing and why it doesn't show a checkbox.
In the old code, I misunderstood the `$args->{mega_partner}` here:
https://github.com/MoveOnOrg/motrunk1/blob/soak/lib/MO/SignOn/PetitionApp.pm#L530
I thought that was for a query parameter.  However it's not -- it's loaded in for mega partners (in `www/pac/signon/dhandler` if you want to see) and then set there.  So it's basically equivalent to petition.mega_partner.....
which in our OSDI-ish api world, that is `creator.source`.
I change the tests to …
> fix hide/show optin bug and get a special link for the link share

- src/components/wrapper.js
Fixes #173. Nav logo relies on moveon-petitions class, which was previously only wrapped around content, not nav. Since that class is on every page, just adding it to wrapper solves it. But not removing it from individual page components because some CSS selectors require the class to be on the same element as page-specific classes.
> add moveon-petitions class on wrapper

- css/moui.css
- src/components/signature-list.js
Fixes #183. I tried to avoid needing CSS updates, but the `a:link` selector doesn't attach to `<a>` tags without href, and href is hard (impossible?) to stop in React.
I also suspect both the empty `<a>` and the `&gt; &gt;` (matching the live site) are bad for accessibility, but we're redesigning soon anyway, so just sticking to the status quo for now.
> update HTML and CSS for signature pager links

- src/components/nav.js
- src/components/wrapper.js
This will help with   #201 and  #63
but will wait until #224 lands, and then we can add the `minimalNav` property to routes.js on /thanks and /create_start without a merge conflict.
(Originally connected in #200)
> minimal nav feature based on property in route

- src/components/wrapper.js
This was throwing a warning for me, and we access `props.routes` as an array, so I think it was just a typo
> Correct PropType for Wrapper

- .travis.yml
- src/routes.js
This PR is a public service announcement to the 'new regime' on static deployment.
Basically giraffe, mop static files, mop-frontend (along with css/moui.css) need to be deployed to different places on mop-static-stage and on production they will go to the same places on static.moveon.org s3 bucket.
We will need to retire mop-static s3 bucket at some point.
> move travis stage target to match our naming scheme

- .travis.yml
- package.json
- test-setup.js
- test/components/giraffe-nav.js
Does two things:
1. Makes travis run tests twice, once with the legacy theme, once with giraffe theme. It's kind of annoying to have to run tests twice, but I don't see a way around it. If we want to build two javascript files, we should run tests for both.
2. Uses `require-hacker` to make importing SVGs work by replacing them with null components in tests.
> Setup for giraffe tests

- .travis.yml
I originally had this in https://github.com/MoveOnOrg/mop-frontend/pull/291/commits/2ec10f4a028d5013c6cd2acd80fc6d6a6d2ebb54, but I accidentally deleted it in a merge conflict
> Add static.moveon.org as static_root on stage

- src/routes.js
Hopefully alleviates and/or fixes https://github.com/MoveOnOrg/mop-frontend/issues/301
Changing this means that submitting a signature will bring you to the reimplemented Thanks route instead of redirecting you to petitions.moveon.org/thanks.html.
> Mark Thanks route production ready

- package.json
- src/store/configureStore.js
See https://github.com/leoasis/redux-immutable-state-invariant
Only included in development.
> Redux middleware that spits an error on you when you try to mutate your state either inside a dispatch or between dispatches. For development use only!
>Because you're not allowed to mutate your state in your reducers!
I tested it out and without @lady3bean's bug fix in https://github.com/MoveOnOrg/mop-frontend/pull/302, and we would have seen this error when clicking into the petition sign page:
```
browser.js:40 Uncaught Error: A state mutation was detected inside a dispatch, in the path: 
`petitionStore.petitions.95983.slug`. Take a look at the reducer(s) handling the action
{"type":"FETCH_PETITION_SUCCESS","petition":{...}.
(http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-a …
```
> Warn about redux state modifications in dispatches

- src/routes.js
Turns out you have to leave of the leading slash in nested routes for it to respect the parent route, otherwise it just tries to match the entire path.
Seems weird to me, but I traced the code to find this:
https://github.com/ReactTraining/react-router/blob/07d6b50ab9a9b6d1940d67abe530044be7f7dc99/modules/matchRoutes.js#L126-L127
Fixes #318
> Fix nested routing

- src/components/theme-giraffe/petition.js
- src/components/theme-giraffe/signature-add-form.js
- src/containers/sign-petition.js
- src/containers/signature-add-form.js
- src/giraffe-ui/modal.js
- src/giraffe-ui/petition/input-block.js
Adds the fixed-position "sign now" button, and the signing modal that is used for mobile petition signing.
On desktop, instead of showing the modal, we focus the sign form.
Tracking issue #309
> Add giraffe mobile signing modal

- src/routes.js
This uses our overwritten <Link> routes and router.push() matcher to rewrites match locations to include baseAppPath (like /2018/). This means you should stay within the baseAppPath you originally accessed.
If a route is not found or not prodReady, we redirect using the original path  like petitions.moveon.org/thanks.html (without /2018/)
Fixes #343
> Rewrite history match location in include baseAppPath

- docs/REFERENCE--environment_variables.md
- src/config.js
- webpack.config.js
It's good because it matches production more closely.
Will default to browser routing in dev and prod.
> Use browser routing by default in dev

- src/actions/petitionActions.js
> update sharetracking for newer google analytics api: gtag instead of _gaq

- src/components/theme-legacy/form/state-select.js
- src/components/theme-legacy/form/target-select/state.js
- src/giraffe-ui/petition/state-select.js
- src/lib/index.js
- src/lib/state-abbrev.js
Gives the bool param `onlyStates` to StateSelect.
So you can only target the elected officials of the 50 states, matching legacy.
We also use StateSelect for search and signing, to which we don't pass `onlyStates`, so it has other regions, matching legacy.
> Show only 50 states in petition target dropdown

- package.json
This gives us a command to check test coverage, as a step toward improving coverage. It also removes the test1 script. Looking at the commit history, I'm not clear why test1 was originally added, so using this PR to at least clarify that, if not remove it.
> add nyc and test:coverage, remove (unused?) test1

- src/actions/petitionActions.js
- src/lib/index.js
Fixes #363 (in terms of loading)
It seems this load event fires when all page dependencies have been loaded, so it won't count things like JS parsing and rendering.
For that it seems we would have to set a variable to Date.now() when the page first renders, which could go along with #348, as there is nothing useful listed on https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming
Let me know if you want me to include rendering or if this is good enough for now.
> Pass page load time (in ms) along with signature request

- src/actions/sessionActions.js
- src/containers/wrapper.js
- src/routes.js
First I tried refactoring routes() to a class, but it didn't work out since the current location wasn't available outside <Router> 🚯 
This should still be fairly discoverable, with the comment in loadSession
fixes #348
> Move loadSession to wrapper so it only fires once

- src/actions/petitionActions.js
(had to do this again because we changed to stringifyParams)
> Don't send undefined values for share tracking

- src/actions/sessionActions.js
fixes #369 so we should have the full url in `page`
We want to track regardless of the action, because pushes will fire when they navigate to a new page, and pops (only) will fire when they go back
> Track on history push and pop, pass page as pathname

- src/actions/petitionActions.js
- src/components/theme-legacy/thanks.js
- src/containers/thanks-next-petition.js
- src/containers/thanks.js
- test/components/thanks.js
If nextPetition (from a top-petitions request) was not loaded when the window focused after sharing (probably because of a slow request), the countdown would not start.
This changes it to start the background interval regardless of the top-petitions request. However, if there is some error with that request, the message still won't be shown (guarded in the render method) and they won't be redirected when the interval finishes (guarded in `redirectToNext()`)
Fixes #359
> Make sure ThanksNextPetition interval is set on focus

- src/components/theme-giraffe/signature-add-form.js
- src/components/theme-legacy/signature-add-form.js
- src/containers/signature-add-form.js
- src/giraffe-ui/petition/input-block.js
Previously, we weren't passing the value in the state to be set as the checkbox's default value.
Additionally, toggling of the checkbox wasn't updating the state correctly.
> Pass thirdPartyOptin correctly to sign form, handle toggling correctly

- src/components/theme-giraffe/static.js
- src/containers/static.js
Gives 10 columns to content on desktop. Full width on mobile.
Fixes #329
> Add margin to giraffe static pages

- src/actions/sessionActions.js
We were using `page` before, which is wrong.
See https://github.com/segmentio/analytics.js/blob/b237600d802e8d1afda7e7a27baec5998fc05471/analytics.js#L6499
Fixes #411 
Also in mop https://github.com/MoveOnOrg/mop/pull/333
> Fix segment tracking to override canonical url

- src/lib/index.js
- src/routes.js
Fixes #414 
This seems like a good default behavior. For me, in chrome at least, the browser overrides this when I go back a page (it maintains previous scroll position).
Also the search results page has it's own scroll behavior for pagination, and that still works (it must fire after the route onChange)
If we want more complicated logic in the future, we can look into https://github.com/taion/react-router-scroll
> Scroll to top on route change

- src/components/theme-legacy/nav.js
- src/components/theme-legacy/wrapper.js
- src/containers/cobrand-logo.js
- src/containers/nav.js
- src/containers/wrapper.js
- src/reducers/nav.js
- test/components/cobrand-logo.js
- test/reducers/nav.js
Add a CobrandLogo container that responds to to the organization in the url or loaded petition …
This will display an org logo if there is an orgName specified in the url or the currently loaded petition has a creator.organzation or sponsor.organization.
See this commit for why this wasn't working before https://github.com/MoveOnOrg/mop-frontend/commit/4940e2f3400db9d816b6e18190548f3be62162ae
Fixes #413
> Fix partner logos

- src/components/theme-giraffe/signature-add-form.js
- src/components/theme-legacy/signature-add-form.js
- src/containers/sign-petition.js
- src/containers/signature-add-form.js
fixes #430 
It turns out all the times the org should be listed, it's done on the backend.
> avoid double organization name

- src/containers/sign-petition.js
Apparently the ref still existed when the input elements were conditionally hidden.
https://developer.mozilla.org/en-US/docs/Web/API/Node/contains
Fixes #435
> Sign now button fix: Check to see if the form ref is still in the body

- src/containers/sign-petition.js
I'd like to understand why this is happening (2018r should be in base app path, so not being matched) not to mention, why FF only.
But this will fix it for now
> Temp fix firefox redirect

- package.json
- src/containers/signature-add-form.js
- src/lib/index.js
Fixes #453 
Uses [email-regex](https://github.com/sindresorhus/email-regex/blob/master/index.js)
```
/^[^\.\s@:][^\s@:]*(?!\.)@[^\.\s@]+(?:\.[^\.\s@]+)*$/
> t.test('justin@example.com')
true
> t.test('justin@example .com')
false
> t.test('justin@example..com')
false
> t.test('foo@yahoo.com h')
false
> t.test('foo+123@yahoo.com')
true
> t.test('é13@yahoo.com')
true
```
> Better email validation

- src/actions/sessionActions.js
Segment.io seems to be pretty lame with their own anon id, and it fails on iOS devices
> track anonymous sessions across pages, too.  

- docs/EXPLANATION--error-handling.md
- src/actions/petitionActions.js
- src/actions/serverErrorActions.js
- src/actions/staticPageActions.js
- src/components/theme-giraffe/error404.js
- src/components/theme-giraffe/error500.js
- src/components/theme-giraffe/wrapper.js
- src/components/theme-legacy/error404.js
- src/components/theme-legacy/error500.js
- src/components/theme-legacy/wrapper.js
- src/containers/wrapper.js
- src/lib/index.js
- src/reducers/error.js
- src/reducers/index.js
- src/routes.js
Closes partially #412 
I added some docs here https://github.com/MoveOnOrg/mop-frontend/blob/5832a82a8a1c04f66d5071c5fdfb446680cbecf9/docs/EXPLANATION--error-handling.md
> Add error pages and routes

- docs/EXPLANATION--error-handling.md
- src/actions/serverErrorActions.js
- src/reducers/error.js
- src/routes.js
Fix for #450 
We need to clear the error in the router's `onChange` callback, so if the user navigates to another page, or goes back or something, this error is cleared and they can see page contents again.
> Clear any error in redux on route change

- src/actions/sessionActions.js
For completely anonymous visits we weren't tracking this because they don't even have a cookie.
This should fix that.
> anonymous segment tracking -- even if we do not have a cookie, etc

- .gitignore
- package.json
- src/actions/petitionActions.js
- src/containers/signature-add-form.js
- src/containers/wrapper.js
- src/lib/index.js
- src/reducers/error.js
- test/actions/petitionActions.js
Adds tests and refactors signPetition to dispatch error actions on bad things from SQS. We also add this failure to the reducer so an error screen will be shown in this case.
We handle errors in a similar way to https://github.com/MoveOnOrg/mop-frontend/pull/450
closes #412
> Error handling for submitting signatures

- .babelrc
- package.json
- src/components/theme-legacy/petition-report.js
- src/containers/petition-report.js
Apparently using `modules: false` stops babel from making cjs modules and allows webpack to optimize the modules itself, which includes tree shaking.
https://wetainment.com/tree-shaking/
Saves us a cool 17kb on the main bundle. 226kb -> 209kb
It also found a module bug somehow 😁
> Make sure tree shaking is working

- src/components/theme-giraffe/footer.js
- src/components/theme-giraffe/nav.js
- src/giraffe-ui/footer/pac-fine-print.js
- src/giraffe-ui/footer/social.js
- src/giraffe-ui/footer/text.js
- src/giraffe-ui/nav/navlink.js
Makes links that go outside of petitions use regular `<a href/>` instead of react router `<Link/>`
This was working in some cases before, because of how we patched `location.push`, but it turns out that it was in other cases matching routes based on the path, regardless of the domain, leading to things like #477, caused by `<Link to='https://store.moveon.org/'>` matching `<Route path='/'>`.
These external links would only redirect if they didn't match any routes. We could have fixed this by adding more special cases to our `location.push` code, but additionally react router was warning us about this:
```
Warning: A path must be pathname + search + hash only, not a full URL like "https://front.moveon.org/#join"
```
So I decided it's better to work with react-router closer to how it …
> Fix external links sometimes not working

- src/actions/petitionActions.js
- src/components/theme-legacy/signature-add-form.js
- src/containers/signature-list.js
Steps to reproduce:
1. Visit https://petitions.moveon.org
1. Click on a top petition
1. See that the first page of signatures isn't loaded.
This is because we cache the top petitions in the petitionStore without the slug key, as opposed to regularly loaded petitions, which get their slug from here https://github.com/MoveOnOrg/mop-frontend/blob/main/src/reducers/index.js#L68-L69.
This breaks the signature list, which tries to try to load the signatures using petition.slug https://github.com/MoveOnOrg/mop-frontend/blob/main/src/containers/signature-list.js#L84
To fix, we use petition.name instead of petition.slug (also everywhere else it's used)
> Fix loading of signatures when navigating to a petition from homepage

- src/components/theme-giraffe/nav.js
This actually points to the right place right now, but in case it changes in the future e.g. to a wordpress page that is easier to edit, this will use the proxy-configured link instead. Closes #491
> updated nav campaign tips link to proxy version

- src/components/theme-giraffe/nav.js
- src/giraffe-ui/nav/navlink.js
By calling `close()` when `<Link>` is clicked.
fixes #503 
I looked into updating to react 16.3 so we could use Context for this (so NavLink components could read the context and call `close()` without being passed it directly), but the way we use enzyme was giving a lot of issues :(
> Close the mobile menu when navigating internally

- test/components/signature-add-form.js
fixes #486 
The behavior was changed and the tests disabled in https://github.com/MoveOnOrg/mop-frontend/pull/463
> Fix tests on the hiding of signature form inputs

- docs/EXPLANATION--error-handling.md
- src/actions/petitionActions.js
- src/containers/cobrand-logo.js
- src/containers/sign-petition.js
- src/containers/wrapper.js
- src/lib/index.js
- src/reducers/index.js
- src/routes.js
- test/components/cobrand-logo.js
- test/store/petition-load.js
fixes #485 
As a follow up to https://github.com/MoveOnOrg/mop-frontend/pull/484, where we made nothing depend on petition.slug, I figured it would be good to remove it from the store.
I also changed all references from "slug" to "name" as, in my opinion, it's better to match what is returned from the API, even if the name isn't perfect.
> Remove all references to petition 'slug' and replace with 'name'

- local/api/v1/targets.json
- src/components/theme-legacy/create-petition-form.js
- src/components/theme-legacy/form/target-select/custom.js
- src/components/theme-legacy/form/target-select/index.js
- src/components/theme-legacy/form/target-select/legislator-autocomplete.js
- src/components/theme-legacy/form/target-select/national.js
- src/components/theme-legacy/form/target-select/state.js
- src/containers/create-petition-target.js
- src/containers/create-petition.js
- src/reducers/petition-targets.js
- test/components/create-petition-target.js
- test/components/create-petition.js
To support /petition_revise.html, plus a cleaner way of doing it overall, an initialPetition can be passed to CreatePetition and the petition targets are analyzed as to whether they are national, state, or custom in CreatePetitionTargets in order to set the right state for the petition target checkboxes and such.
The national and state target forms know if the targets are "default" (shown as a checkbox) or otherwise pass them to the autocomplete component. It also handles showing any already selected targets as pre-checked checkboxes.
Note that this will be merged into the create-petitions branch.
This one still just submits the petition into the redux state. I'll open other PRs that add previewing, revising, and submitting to the API. It should be fine to merge this to `main` for testing …
> Refactor target select

- src/actions/createPetitionActions.js
Ideally when https://github.com/MoveOnOrg/mop/pull/405 is merged, this will just work(TM) because we already have this code
https://github.com/MoveOnOrg/mop-frontend/blob/3c433a5ad9e296ba5fe6f3ecd705846388432bb3/src/components/theme-legacy/form/target-select/national.js#L6-L7
> Request fed targets for national target requests

- src/components/theme-legacy/create-preview.js
- src/components/theme-legacy/register-form.js
- src/components/theme-legacy/register.js
- src/config.js
- src/containers/create-petition.js
- src/containers/create-preview.js
- src/containers/register-form.js
- src/loaders/index.js
- src/routes.js
Adds the create_preview.html route, which previews the petition in the redux store (that you presumably just created at create_start.html).
I refactored the register page so that `LegacyTheme/register` is just the wrapper with the things on the register page for RegisterForm, which contains all the inputs and logic.
This is so we can also include RegisterForm on PetitionPreview, so people can register as they create a petition.
Still to come is the logic for submitting the petition to the API, plus the form that is shown instead of RegisterForm if you are logged in.
I will also need to rebase https://github.com/MoveOnOrg/mop-frontend/pull/493 on this one (just for the /register refactor, there's still no giraffe create-petition)
Closes #339
> Preview petition

- src/components/theme-legacy/create-preview.js
- src/components/theme-legacy/form/target-select/state.js
- src/containers/create-preview.js
- src/containers/create-revise.js
- src/loaders/index.js
- src/routes.js
- test/components/create-petition.js
- test/components/create-preview.js
- test/components/create-revise.js
Adds the create-revise route and container, which basically just wraps CreatePetition and passes an initialPetition from the redux state.
Plus a few fixes for targets to show up correctly when they are being revised.
Plus some tests for previewing and revision.
> Ability to revise petition during creation

- src/containers/signature-add-form.js
- test/components/signature-add-form.js
first, show all the fields after there is a validation error
second, always show all the fields if the user doesn't have an address and the petiton needs one
fixes #541
> Show signing fields if address is required

- src/components/theme-legacy/create-petition-form.js
- src/containers/create-petition-target.js
- src/containers/create-petition.js
As discovered in #550, the input fields for a custom target should be added as a custom target.
I've opted to add these input fields into the `state.target` array on submit, if they exist, before the verification and the submission to the redux store occurs.
This means that the target moves from the fields to a checkbox if the verification fails and on revision. Hope this is OK.
To do this, I've moved the custom input fields state up into the CreatePetition component.
fixes #550.
> Add custom target input fields to target list before verification

- docs/REFERENCE--environment_variables.md
- src/actions/createPetitionActions.js
- src/components/theme-legacy/create-petition-form.js
- src/config.js
- src/containers/create-petition.js
- src/reducers/petition-create.js
- webpack.config.js
Uses env var GTAG_PETITION_CREATE  for the `send_to` param for tracking petition create conversions to Google.
Allows source, cloned_from_id, and solicit_id to be submitted along with the petition create request if set in the query parameters of create_start.html. Shouldn't include them in the request if not set.
closes #556 
closes #557
> Petition create tracking

- .travis.yml
For faster builds.
I don't think (?) it will mess anything up, because it will still run `npm install`, just with the `node_modules` folder already the same as last build.
https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
> Have travis cache node_modules

- src/actions/createPetitionActions.js
- src/components/theme-giraffe/edit-user-form.js
- src/components/theme-legacy/create-preview.js
- src/containers/create-petition.js
- src/containers/create-preview.js
Some of #552, where we deal with where the user is fully authenticated and does OR does not have a zip code.
I don't handle this yet, but I probably could in a similar way to the zip code: (once I get my local api working again)
>  if the user has an akid / guest login but is not authenticated, then we will also need to ask them to set a password, but don't need to ask name/etc
~I haven't tested with a real API yet, so if someone wants to test locally, that would be great.~ Now tested locally, and it seems to be working.
> Support authenticated users when creating a petition

- src/containers/signature-add-form.js
hopefully closes #560, but doesn't really get to the root of the problem as to why people are filling "name" with emails. I tried to reproduce in mobile safari, but couldn't.
> On signing, validate that the name is not an email address

- src/giraffe-ui/petition/state-select.js
The wrong label messed it up in Firefox. How dare they actually check the html 😛 
closes #328
> Fix autofill for signing a petition in firefox

- src/routes.js
In order to test on FB, or per petition, we need the ability to trigger it per petition vs per all petitions. I suggest adding 'sms' in the querystring (could even appear as `source=sms`) in order to enable random cohort rendering.
> Allows someone to add sms in qs in order to add random cohort

- package.json
https://github.com/plotly/dash-component-boilerplate/issues/12
`TypeError: Cannot read property 'properties' of undefined `
> update webpack-cli after getting build error on main

- src/components/theme-giraffe/signature-add-form.js
- src/containers/signature-add-form.js
- src/lib/index.js
- test/components/signature-add-form.js
This is to reduce errors when people enter their email address and sometimes have a typo in the domain name.
This adds immediate feedback for the name and email fields (rather than waiting for submitting) and in the case of an 'off-by-1' difference for common domains, we suggest the more common domain in red (but don't block submission)
> Suggest common domains with typos

- docs/REFERENCE--environment_variables.md
- src/components/theme-giraffe/messenger-button.js
- src/components/theme-giraffe/thanks.js
- src/config.js
- src/containers/hoc-messenger.js
- src/containers/thanks.js
- src/giraffe-ui/svgs/messenger.svg
- webpack.config.js
I need to take the whatsapp button out to test the messenger button separately; some notes below:
- This contains a lot of the logic in #606 
- This doesn't completely rip out whatsapp work because we're still making a decision about whether to keep testing the button. There's a scenario where we could still test messenger and whatsapp.
- This changes the experiment to `messenger2` and populates the messenger table for testing
- This button only appears on mobile when cohort=1
Screen Shot on Mobile:
> 595 messenger share wo whatsapp
